import { buildPayrollJournal } from "@/lib/accounting/engine";
import {
  demoAttendance,
  demoBusiness,
  demoEmployees,
  demoJournalEntries,
  demoPeriod,
  demoStockMovements,
  demoTaxProfile,
  demoWarehouses,
} from "@/lib/demo-data";
import type { ErpWorkspace } from "@/lib/erp/types";
import {
  buildPurchaseBillJournal,
  buildSalesInvoiceJournal,
  calculateErpMetrics,
  buildErpTasks,
  buildPaymentJournal,
  movementFromPurchaseBill,
  movementFromSalesInvoice,
} from "@/lib/erp/operations";
import {
  buildFixedAssetAcquisitionJournal,
  buildFixedAssetDepreciationJournal,
  monthlyDepreciation,
} from "@/lib/erp/fixed-assets";
import { buildLocationMetrics, featureFlagsForTemplate, industryTemplates, summarizeRawTransactions } from "@/lib/erp/horizontal";
import { systemAccounts } from "@/lib/accounting/chart";
import { permissionsForRole } from "@/lib/security/permissions";

export function createDemoErpWorkspace(): ErpWorkspace {
  const products: ErpWorkspace["products"] = [
    {
      id: "item-rendang",
      businessId: demoBusiness.id,
      sku: "FNB-RND-250",
      name: "Rendang Bowl",
      variant: "250g",
      unit: "porsi",
      trackStock: true,
      productType: "stock_item",
      industryItemType: "menu_item",
      fulfillmentMethod: "recipe_on_sale",
      makeOrBuy: "make",
      defaultWarehouseId: "wh-kitchen",
      category: "Makanan siap jual",
      sellingPrice: 45_000,
      purchasePrice: 20_000,
      reorderPoint: 40,
      safetyStock: 20,
      minimumOrderQty: 50,
      leadTimeDays: 1,
      productionLeadTimeDays: 1,
      isSellable: true,
      isPurchasable: true,
    },
    {
      id: "item-teh",
      businessId: demoBusiness.id,
      sku: "DRK-TEH-350",
      name: "Es Teh Nusantara",
      variant: "350ml",
      unit: "botol",
      trackStock: true,
      productType: "stock_item",
      industryItemType: "menu_item",
      fulfillmentMethod: "recipe_on_sale",
      makeOrBuy: "make",
      defaultWarehouseId: "wh-booth",
      category: "Minuman",
      sellingPrice: 15_000,
      purchasePrice: 3_500,
      reorderPoint: 120,
      safetyStock: 80,
      minimumOrderQty: 100,
      leadTimeDays: 1,
      productionLeadTimeDays: 0,
      isSellable: true,
      isPurchasable: true,
    },
    {
      id: "svc-catering",
      businessId: demoBusiness.id,
      sku: "SVC-CATERING",
      name: "Jasa Catering Event",
      unit: "paket",
      trackStock: false,
      productType: "service",
      industryItemType: "service_item",
      fulfillmentMethod: "non_stock",
      makeOrBuy: "buy",
      defaultWarehouseId: "wh-kitchen",
      category: "Jasa",
      sellingPrice: 2_500_000,
      purchasePrice: 0,
      reorderPoint: 0,
      safetyStock: 0,
      minimumOrderQty: 0,
      leadTimeDays: 0,
      productionLeadTimeDays: 0,
      isSellable: true,
      isPurchasable: false,
    },
    {
      id: "item-beef",
      businessId: demoBusiness.id,
      sku: "BB-DAGING",
      name: "Daging sapi",
      unit: "kg",
      trackStock: true,
      productType: "stock_item",
      industryItemType: "raw_material",
      fulfillmentMethod: "buy_stock",
      makeOrBuy: "buy",
      defaultWarehouseId: "wh-kitchen",
      category: "Bahan baku",
      sellingPrice: 0,
      purchasePrice: 125_000,
      reorderPoint: 12,
      safetyStock: 8,
      minimumOrderQty: 10,
      leadTimeDays: 2,
      productionLeadTimeDays: 0,
      isSellable: false,
      isPurchasable: true,
    },
    {
      id: "item-rice",
      businessId: demoBusiness.id,
      sku: "BB-BERAS",
      name: "Beras matang",
      unit: "kg",
      trackStock: true,
      productType: "stock_item",
      industryItemType: "raw_material",
      fulfillmentMethod: "buy_stock",
      makeOrBuy: "buy",
      defaultWarehouseId: "wh-kitchen",
      category: "Bahan baku",
      sellingPrice: 0,
      purchasePrice: 14_000,
      reorderPoint: 25,
      safetyStock: 15,
      minimumOrderQty: 25,
      leadTimeDays: 1,
      productionLeadTimeDays: 0,
      isSellable: false,
      isPurchasable: true,
    },
    {
      id: "item-tea-leaf",
      businessId: demoBusiness.id,
      sku: "BB-TEH",
      name: "Teh seduh",
      unit: "kg",
      trackStock: true,
      productType: "stock_item",
      industryItemType: "raw_material",
      fulfillmentMethod: "buy_stock",
      makeOrBuy: "buy",
      defaultWarehouseId: "wh-booth",
      category: "Bahan baku",
      sellingPrice: 0,
      purchasePrice: 80_000,
      reorderPoint: 4,
      safetyStock: 2,
      minimumOrderQty: 5,
      leadTimeDays: 2,
      productionLeadTimeDays: 0,
      isSellable: false,
      isPurchasable: true,
    },
    {
      id: "item-cup",
      businessId: demoBusiness.id,
      sku: "KM-CUP-350",
      name: "Cup 350ml",
      unit: "pcs",
      trackStock: true,
      productType: "stock_item",
      industryItemType: "raw_material",
      fulfillmentMethod: "buy_stock",
      makeOrBuy: "buy",
      defaultWarehouseId: "wh-booth",
      category: "Kemasan",
      sellingPrice: 0,
      purchasePrice: 650,
      reorderPoint: 200,
      safetyStock: 100,
      minimumOrderQty: 500,
      leadTimeDays: 3,
      productionLeadTimeDays: 0,
      isSellable: false,
      isPurchasable: true,
    },
  ];

  const productStructures: ErpWorkspace["productStructures"] = [
    {
      id: "recipe-rendang-bowl",
      businessId: demoBusiness.id,
      parentProductId: "item-rendang",
      type: "recipe",
      outputQuantity: 1,
      yieldPercent: 95,
      isActive: true,
      notes: "HPP otomatis untuk satu porsi Rendang Bowl.",
      updatedAt: "2026-06-01T00:00:00.000Z",
      lines: [
        {
          id: "recipe-rendang-beef",
          businessId: demoBusiness.id,
          structureId: "recipe-rendang-bowl",
          componentProductId: "item-beef",
          quantity: 0.12,
          wastePercent: 5,
          unitCostSnapshot: 125_000,
        },
        {
          id: "recipe-rendang-rice",
          businessId: demoBusiness.id,
          structureId: "recipe-rendang-bowl",
          componentProductId: "item-rice",
          quantity: 0.18,
          wastePercent: 2,
          unitCostSnapshot: 14_000,
        },
      ],
    },
    {
      id: "recipe-es-teh",
      businessId: demoBusiness.id,
      parentProductId: "item-teh",
      type: "recipe",
      outputQuantity: 1,
      yieldPercent: 98,
      isActive: true,
      notes: "Bahan minuman dan kemasan per botol/cup.",
      updatedAt: "2026-06-01T00:00:00.000Z",
      lines: [
        {
          id: "recipe-teh-leaf",
          businessId: demoBusiness.id,
          structureId: "recipe-es-teh",
          componentProductId: "item-tea-leaf",
          quantity: 0.015,
          wastePercent: 3,
          unitCostSnapshot: 80_000,
        },
        {
          id: "recipe-teh-cup",
          businessId: demoBusiness.id,
          structureId: "recipe-es-teh",
          componentProductId: "item-cup",
          quantity: 1,
          wastePercent: 1,
          unitCostSnapshot: 650,
        },
      ],
    },
  ];

  const demandForecasts: ErpWorkspace["demandForecasts"] = [
    {
      id: "forecast-rendang-july",
      businessId: demoBusiness.id,
      productId: "item-rendang",
      locationId: "loc-kitchen",
      periodStart: "2026-07-01",
      periodEnd: "2026-07-31",
      quantity: 900,
      source: "manual",
      notes: "Target event dan walk-in Juli.",
      createdAt: "2026-06-25T00:00:00.000Z",
    },
    {
      id: "forecast-teh-july",
      businessId: demoBusiness.id,
      productId: "item-teh",
      locationId: "loc-booth",
      periodStart: "2026-07-01",
      periodEnd: "2026-07-31",
      quantity: 1_600,
      source: "manual",
      notes: "Forecast booth bulan depan.",
      createdAt: "2026-06-25T00:00:00.000Z",
    },
  ];

  const mrpRuns: ErpWorkspace["mrpRuns"] = [
    {
      id: "mrp-july",
      businessId: demoBusiness.id,
      name: "MRP Juli 2026",
      periodStart: "2026-07-01",
      periodEnd: "2026-07-31",
      status: "planned",
      createdAt: "2026-06-25T00:00:00.000Z",
    },
  ];

  const mrpRecommendations: ErpWorkspace["mrpRecommendations"] = [];
  const productionOrders: ErpWorkspace["productionOrders"] = [];

  const customers: ErpWorkspace["customers"] = [
    {
      id: "cust-001",
      businessId: demoBusiness.id,
      code: "CUST-001",
      name: "PT Event Ceria",
      phone: "0812-1000-2000",
      email: "finance@eventceria.test",
      address: "Jakarta Selatan",
      creditLimit: 20_000_000,
      isActive: true,
    },
    {
      id: "cust-002",
      businessId: demoBusiness.id,
      code: "CUST-002",
      name: "Booth Walk-in",
      phone: "0811-2222-3333",
      creditLimit: 0,
      isActive: true,
    },
  ];

  const suppliers: ErpWorkspace["suppliers"] = [
    {
      id: "sup-001",
      businessId: demoBusiness.id,
      code: "SUP-001",
      name: "CV Bumbu Nusantara",
      phone: "0812-3000-4000",
      address: "Jakarta Timur",
      isActive: true,
    },
    {
      id: "sup-002",
      businessId: demoBusiness.id,
      code: "SUP-002",
      name: "Toko Kemasan Maju",
      phone: "0813-5000-6000",
      isActive: true,
    },
  ];

  const salesInvoices: ErpWorkspace["salesInvoices"] = [
    {
      id: "sinv-001",
      businessId: demoBusiness.id,
      invoiceNo: "INV-2026-0001",
      customerId: "cust-001",
      date: "2026-06-05",
      dueDate: "2026-06-19",
      status: "partially_paid",
      lines: [
        {
          id: "sinv-line-001",
          productId: "item-rendang",
          warehouseId: "wh-kitchen",
          description: "Rendang Bowl event",
          quantity: 120,
          unitPrice: 45_000,
          cogs: 20_000,
        },
        {
          id: "sinv-line-002",
          productId: "item-teh",
          warehouseId: "wh-booth",
          description: "Es Teh Nusantara event",
          quantity: 120,
          unitPrice: 15_000,
          cogs: 3_500,
        },
      ],
      total: 7_200_000,
      paidAmount: 5_000_000,
      journalEntryId: "journal-sales-001",
      createdAt: "2026-06-05T04:00:00.000Z",
    },
    {
      id: "sinv-002",
      businessId: demoBusiness.id,
      invoiceNo: "INV-2026-0002",
      customerId: "cust-002",
      date: "2026-06-14",
      dueDate: "2026-06-14",
      status: "paid",
      lines: [
        {
          id: "sinv-line-003",
          productId: "item-rendang",
          warehouseId: "wh-kitchen",
          description: "Walk-in booth",
          quantity: 55,
          unitPrice: 45_000,
          cogs: 20_000,
        },
      ],
      total: 2_475_000,
      paidAmount: 2_475_000,
      journalEntryId: "journal-sales-002",
      createdAt: "2026-06-14T08:00:00.000Z",
    },
  ];

  const purchaseBills: ErpWorkspace["purchaseBills"] = [
    {
      id: "pbill-001",
      businessId: demoBusiness.id,
      billNo: "BILL-2026-0001",
      supplierId: "sup-001",
      date: "2026-06-03",
      dueDate: "2026-06-17",
      status: "partially_paid",
      lines: [
        {
          id: "pbill-line-001",
          productId: "item-rendang",
          warehouseId: "wh-kitchen",
          description: "Bahan Rendang Bowl",
          quantity: 280,
          unitCost: 20_000,
        },
      ],
      total: 5_600_000,
      paidAmount: 3_000_000,
      journalEntryId: "journal-purchase-001",
      createdAt: "2026-06-03T03:00:00.000Z",
    },
    {
      id: "pbill-002",
      businessId: demoBusiness.id,
      billNo: "BILL-2026-0002",
      supplierId: "sup-002",
      date: "2026-06-07",
      dueDate: "2026-06-21",
      status: "posted",
      lines: [
        {
          id: "pbill-line-002",
          productId: "item-teh",
          warehouseId: "wh-booth",
          description: "Botol dan bahan minuman",
          quantity: 420,
          unitCost: 3_500,
        },
      ],
      total: 1_470_000,
      paidAmount: 0,
      journalEntryId: "journal-purchase-002",
      createdAt: "2026-06-07T04:00:00.000Z",
    },
  ];

  const payments: ErpWorkspace["payments"] = [
    {
      id: "pay-001",
      businessId: demoBusiness.id,
      direction: "inbound",
      documentType: "sales_invoice",
      documentId: "sinv-001",
      date: "2026-06-06",
      amount: 5_000_000,
      method: "bank_transfer",
      reference: "TRF-INV-0001",
      status: "posted",
      createdAt: "2026-06-06T04:30:00.000Z",
    },
    {
      id: "pay-002",
      businessId: demoBusiness.id,
      direction: "inbound",
      documentType: "sales_invoice",
      documentId: "sinv-002",
      date: "2026-06-14",
      amount: 2_475_000,
      method: "qris",
      reference: "QRIS-BOOTH-014",
      status: "posted",
      createdAt: "2026-06-14T09:30:00.000Z",
    },
    {
      id: "pay-003",
      businessId: demoBusiness.id,
      direction: "outbound",
      documentType: "purchase_bill",
      documentId: "pbill-001",
      date: "2026-06-05",
      amount: 3_000_000,
      method: "bank_transfer",
      reference: "TRF-BILL-0001",
      status: "posted",
      createdAt: "2026-06-05T05:00:00.000Z",
    },
  ];

  const salesJournals = salesInvoices.map(buildSalesInvoiceJournal);
  const purchaseJournals = purchaseBills.map(buildPurchaseBillJournal);
  const paymentJournals = payments.map(buildPaymentJournal);
  const paymentsWithJournals = payments.map((payment, index) => ({
    ...payment,
    journalEntryId: paymentJournals[index].id,
  }));
  const openingJournal = demoJournalEntries[0];
  const payrollJournal = buildPayrollJournal({
    businessId: demoBusiness.id,
    date: "2026-06-25",
    grossPay: 5_500_000,
    netCashPaid: 4_800_000,
    salaryPayable: 400_000,
    taxWithheld: 300_000,
  });
  const payrollRun = {
    id: "payroll-001",
    businessId: demoBusiness.id,
    period: "2026-06",
    employeeId: demoEmployees[0].id,
    grossPay: 5_500_000,
    deductions: 0,
    taxWithheld: 300_000,
    netPay: 4_800_000,
    components: [{ name: "Gaji pokok", amount: 5_500_000, type: "earning" as const }],
    journalEntryId: payrollJournal.id,
  };
  const fixedAssets: ErpWorkspace["fixedAssets"] = [
    {
      id: "asset-oven-001",
      businessId: demoBusiness.id,
      assetNo: "FA-2026-0001",
      name: "Oven produksi 3 deck",
      category: "Peralatan produksi",
      acquisitionDate: "2026-06-01",
      acquisitionCost: 24_000_000,
      residualValue: 2_400_000,
      usefulLifeMonths: 36,
      depreciationMethod: "straight_line",
      acquisitionType: "cash",
      status: "active",
      locationId: "loc-kitchen",
      supplierId: "sup-002",
      notes: "Dipakai untuk produksi harian central kitchen.",
      createdAt: "2026-06-01T03:00:00.000Z",
    },
  ];
  const fixedAssetAcquisitionJournal = buildFixedAssetAcquisitionJournal({
    businessId: demoBusiness.id,
    assetId: fixedAssets[0].id,
    assetNo: fixedAssets[0].assetNo,
    date: fixedAssets[0].acquisitionDate,
    amount: fixedAssets[0].acquisitionCost,
    acquisitionType: "cash",
  });
  fixedAssets[0].journalEntryId = fixedAssetAcquisitionJournal.id;
  const fixedAssetDepreciationRuns: ErpWorkspace["fixedAssetDepreciationRuns"] = [
    {
      id: "dep-run-2026-06",
      businessId: demoBusiness.id,
      period: "2026-06",
      date: "2026-06-30",
      status: "posted",
      totalDepreciation: monthlyDepreciation(fixedAssets[0]),
      createdAt: "2026-06-30T02:00:00.000Z",
    },
  ];
  const fixedAssetDepreciationJournal = buildFixedAssetDepreciationJournal({
    businessId: demoBusiness.id,
    runId: fixedAssetDepreciationRuns[0].id,
    period: fixedAssetDepreciationRuns[0].period,
    date: fixedAssetDepreciationRuns[0].date,
    amount: fixedAssetDepreciationRuns[0].totalDepreciation,
  });
  fixedAssetDepreciationRuns[0].journalEntryId = fixedAssetDepreciationJournal.id;
  const fixedAssetDepreciationLines: ErpWorkspace["fixedAssetDepreciationLines"] = [
    {
      id: "dep-line-oven-2026-06",
      businessId: demoBusiness.id,
      runId: fixedAssetDepreciationRuns[0].id,
      assetId: fixedAssets[0].id,
      period: fixedAssetDepreciationRuns[0].period,
      amount: fixedAssetDepreciationRuns[0].totalDepreciation,
      accumulatedDepreciation: fixedAssetDepreciationRuns[0].totalDepreciation,
      bookValue: fixedAssets[0].acquisitionCost - fixedAssetDepreciationRuns[0].totalDepreciation,
      createdAt: "2026-06-30T02:00:00.000Z",
    },
  ];
  const ingredientStockMovements: ErpWorkspace["stockMovements"] = [
    {
      id: "sm-ing-beef-1",
      businessId: demoBusiness.id,
      itemId: "item-beef",
      warehouseId: "wh-kitchen",
      date: "2026-06-01",
      type: "purchase",
      quantity: 90,
      value: 11_250_000,
      memo: "Opening bahan baku",
    },
    {
      id: "sm-ing-rice-1",
      businessId: demoBusiness.id,
      itemId: "item-rice",
      warehouseId: "wh-kitchen",
      date: "2026-06-01",
      type: "purchase",
      quantity: 160,
      value: 2_240_000,
      memo: "Opening bahan baku",
    },
    {
      id: "sm-ing-tea-1",
      businessId: demoBusiness.id,
      itemId: "item-tea-leaf",
      warehouseId: "wh-booth",
      date: "2026-06-01",
      type: "purchase",
      quantity: 22,
      value: 1_760_000,
      memo: "Opening bahan baku",
    },
    {
      id: "sm-ing-cup-1",
      businessId: demoBusiness.id,
      itemId: "item-cup",
      warehouseId: "wh-booth",
      date: "2026-06-01",
      type: "purchase",
      quantity: 2_800,
      value: 1_820_000,
      memo: "Opening kemasan",
    },
  ];
  const stockMovements = [
    ...demoStockMovements,
    ...ingredientStockMovements,
    ...salesInvoices.flatMap(movementFromSalesInvoice),
    ...purchaseBills.flatMap(movementFromPurchaseBill),
  ];
  const locations: ErpWorkspace["locations"] = [
    {
      id: "loc-kitchen",
      businessId: demoBusiness.id,
      code: "OUT-001",
      name: "Central Kitchen",
      type: "outlet",
      warehouseId: "wh-kitchen",
      isActive: true,
    },
    {
      id: "loc-booth",
      businessId: demoBusiness.id,
      code: "OUT-002",
      name: "Booth Event",
      type: "store",
      warehouseId: "wh-booth",
      isActive: true,
    },
  ];
  const transactionSources: ErpWorkspace["transactionSources"] = [
    {
      id: "source-pos-kitchen",
      businessId: demoBusiness.id,
      locationId: "loc-kitchen",
      sourceType: "pos_csv",
      name: "POS Central Kitchen",
      isActive: true,
    },
    {
      id: "source-marketplace",
      businessId: demoBusiness.id,
      locationId: "loc-booth",
      sourceType: "marketplace_csv",
      name: "Marketplace & QRIS Booth",
      isActive: true,
    },
  ];
  const rawImportBatches: ErpWorkspace["rawImportBatches"] = [
    {
      id: "raw-batch-001",
      businessId: demoBusiness.id,
      locationId: "loc-booth",
      source: "pos_csv",
      status: "summarized",
      totalRows: 5,
      validRows: 5,
      duplicateRows: 0,
      errorRows: 0,
      createdAt: "2026-06-14T10:00:00.000Z",
    },
  ];
  const rawTransactions: ErpWorkspace["rawTransactions"] = [
    {
      id: "raw-tx-001",
      businessId: demoBusiness.id,
      locationId: "loc-booth",
      batchId: "raw-batch-001",
      source: "pos_csv",
      externalId: "POS-BOOTH-001",
      transactionDate: "2026-06-14",
      status: "summarized",
      grossAmount: 540_000,
      discountAmount: 0,
      netAmount: 540_000,
      taxAmount: 0,
      paymentMethod: "qris",
      customerName: "Walk-in",
      createdAt: "2026-06-14T10:01:00.000Z",
    },
    {
      id: "raw-tx-002",
      businessId: demoBusiness.id,
      locationId: "loc-booth",
      batchId: "raw-batch-001",
      source: "pos_csv",
      externalId: "POS-BOOTH-002",
      transactionDate: "2026-06-14",
      status: "summarized",
      grossAmount: 315_000,
      discountAmount: 15_000,
      netAmount: 300_000,
      taxAmount: 0,
      paymentMethod: "cash",
      customerName: "Walk-in",
      createdAt: "2026-06-14T10:02:00.000Z",
    },
    {
      id: "raw-tx-003",
      businessId: demoBusiness.id,
      locationId: "loc-booth",
      batchId: "raw-batch-001",
      source: "pos_csv",
      externalId: "POS-BOOTH-003",
      transactionDate: "2026-06-14",
      status: "summarized",
      grossAmount: 450_000,
      discountAmount: 0,
      netAmount: 450_000,
      taxAmount: 0,
      paymentMethod: "qris",
      customerName: "Walk-in",
      createdAt: "2026-06-14T10:03:00.000Z",
    },
    {
      id: "raw-tx-004",
      businessId: demoBusiness.id,
      locationId: "loc-booth",
      batchId: "raw-batch-001",
      source: "pos_csv",
      externalId: "POS-BOOTH-004",
      transactionDate: "2026-06-14",
      status: "summarized",
      grossAmount: 225_000,
      discountAmount: 0,
      netAmount: 225_000,
      taxAmount: 0,
      paymentMethod: "qris",
      customerName: "Walk-in",
      createdAt: "2026-06-14T10:04:00.000Z",
    },
    {
      id: "raw-tx-005",
      businessId: demoBusiness.id,
      locationId: "loc-booth",
      batchId: "raw-batch-001",
      source: "pos_csv",
      externalId: "POS-BOOTH-005",
      transactionDate: "2026-06-14",
      status: "summarized",
      grossAmount: 180_000,
      discountAmount: 0,
      netAmount: 180_000,
      taxAmount: 0,
      paymentMethod: "bank_transfer",
      customerName: "Walk-in",
      createdAt: "2026-06-14T10:05:00.000Z",
    },
  ];
  const dailyTransactionSummaries = summarizeRawTransactions(rawTransactions);
  const rawTransactionLines: ErpWorkspace["rawTransactionLines"] = [
    {
      id: "raw-line-001",
      businessId: demoBusiness.id,
      rawTransactionId: "raw-tx-001",
      productId: "item-rendang",
      description: "Rendang Bowl",
      quantity: 12,
      unitPrice: 45_000,
      total: 540_000,
    },
    {
      id: "raw-line-002",
      businessId: demoBusiness.id,
      rawTransactionId: "raw-tx-002",
      productId: "item-teh",
      description: "Es Teh Nusantara",
      quantity: 21,
      unitPrice: 15_000,
      total: 315_000,
    },
  ];
  const rawPayments: ErpWorkspace["rawPayments"] = rawTransactions.map((transaction) => ({
    id: `raw-pay-${transaction.id}`,
    businessId: transaction.businessId,
    rawTransactionId: transaction.id,
    method: transaction.paymentMethod,
    amount: transaction.netAmount,
  }));
  const settlementRecords: ErpWorkspace["settlementRecords"] = [
    {
      id: "settlement-qris-001",
      businessId: demoBusiness.id,
      locationId: "loc-booth",
      source: "pos_csv",
      settlementDate: "2026-06-14",
      method: "qris",
      grossAmount: 1_215_000,
      feeAmount: 8_505,
      netAmount: 1_206_495,
      status: "matched",
    },
  ];

  const baseWorkspace = {
    user: {
      id: "demo-user",
      name: "Ayu Prameswari",
      email: "ayu@rasarapi.test",
      role: "owner" as const,
    },
    permissions: permissionsForRole("owner"),
    business: demoBusiness,
    period: demoPeriod,
    taxProfile: demoTaxProfile,
    accounts: systemAccounts.map((account) => ({ ...account, businessId: demoBusiness.id })),
    locations,
    featureFlags: featureFlagsForTemplate(demoBusiness.id, "food_beverage"),
    industryTemplates,
    transactionSources,
    memberInvites: [],
    customers,
    suppliers,
    products,
    productStructures,
    demandForecasts,
    mrpRuns,
    mrpRecommendations,
    productionOrders,
    warehouses: demoWarehouses,
    salesInvoices,
    purchaseBills,
    payments: paymentsWithJournals,
    paymentAllocations: paymentsWithJournals.map((payment) => ({
      id: `alloc-${payment.id}`,
      businessId: payment.businessId,
      paymentId: payment.id,
      documentType: payment.documentType,
      documentId: payment.documentId,
      amount: payment.amount,
      createdAt: payment.createdAt,
    })),
    stockMovements,
    stockTransfers: [
      {
        id: "transfer-001",
        businessId: demoBusiness.id,
        transferNo: "TRF-STK-0001",
        date: "2026-06-11",
        itemId: "item-teh",
        fromWarehouseId: "wh-kitchen",
        toWarehouseId: "wh-booth",
        quantity: 80,
        status: "posted" as const,
        memo: "Restock booth event",
      },
    ],
    stockAdjustments: [
      {
        id: "adj-001",
        businessId: demoBusiness.id,
        adjustmentNo: "ADJ-2026-0001",
        date: "2026-06-18",
        itemId: "item-rendang",
        warehouseId: "wh-kitchen",
        quantity: -3,
        value: 60_000,
        reason: "Selisih stock opname",
        status: "posted" as const,
      },
    ],
    employees: demoEmployees,
    attendance: demoAttendance,
    payrollRuns: [payrollRun],
    journals: [
      openingJournal,
      fixedAssetAcquisitionJournal,
      fixedAssetDepreciationJournal,
      ...salesJournals,
      ...purchaseJournals,
      ...paymentJournals,
      payrollJournal,
    ],
    importBatches: [
      {
        id: "import-001",
        businessId: demoBusiness.id,
        source: "marketplace_csv" as const,
        status: "preview" as const,
        totalRows: 42,
        validRows: 39,
        duplicateRows: 2,
        errorRows: 1,
        createdAt: "2026-06-20T02:00:00.000Z",
      },
    ],
    rawImportBatches,
    rawTransactions,
    rawTransactionLines,
    rawPayments,
    settlementRecords,
    dailyTransactionSummaries,
    fixedAssets,
    fixedAssetDepreciationRuns,
    fixedAssetDepreciationLines,
    fixedAssetDisposals: [],
    locationMetrics: [],
    attachments: [
      {
        id: "att-file-001",
        businessId: demoBusiness.id,
        ownerType: "sales_invoice" as const,
        ownerId: "sinv-001",
        fileName: "po-event-ceria.pdf",
        storagePath: "demo/po-event-ceria.pdf",
        mimeType: "application/pdf",
        sizeBytes: 240_000,
        createdAt: "2026-06-05T04:15:00.000Z",
      },
    ],
    activities: [
      {
        id: "act-001",
        businessId: demoBusiness.id,
        actorName: "Ayu Prameswari",
        module: "sales" as const,
        action: "posted invoice",
        description: "INV-2026-0001 dipost dan jurnal otomatis dibuat.",
        createdAt: "2026-06-05T04:00:00.000Z",
      },
      {
        id: "act-002",
        businessId: demoBusiness.id,
        actorName: "Dimas",
        module: "inventory" as const,
        action: "stock adjustment",
        description: "Stock opname Rendang Bowl selisih 3 porsi.",
        createdAt: "2026-06-18T03:15:00.000Z",
      },
      {
        id: "act-003",
        businessId: demoBusiness.id,
        actorName: "System",
        module: "tax" as const,
        action: "tax estimate",
        description: "Estimasi PPh final UMKM diperbarui dari omzet posted.",
        createdAt: "2026-06-25T01:00:00.000Z",
      },
    ],
  };

  const metrics = calculateErpMetrics(baseWorkspace);
  const locationMetrics = buildLocationMetrics(baseWorkspace);
  const tasks = buildErpTasks({ ...baseWorkspace, locationMetrics, metrics });

  return {
    ...baseWorkspace,
    locationMetrics,
    tasks,
    metrics,
  };
}
